### ISSUE TITLE
Pangolin v4 output column change issues

### ISSUE THREAD

**Issue by DarianHole** [simpsonlab/ncov-parser#13]
Pangolin V4 column name changes causing issues (as expected)

For the lineage parser, the 'note' column now appears to be 'scorpio_notes'. https://github.com/simpsonlab/ncov-parser/blob/14698f01d3add0b5cd868f0b601f6992c51cfa68/ncov/parser/Lineage.py#L9 and running with pangolin V4 it just returns 'none' for now.

And then as an aside, is there any other columns that should be added? Like the new note column

**Comment by rdeborja** [comment]
Sorry for the delay in this, I've released `ncov-parser` 0.7.0 here and on `pypi.org`.  I fixed the column change for Pangolin 4 while still supporting Pangolin 3.  You can use this version of the package with `ncov-tools` branch `1.9-rc` which supports Pangolin 4 by default but also allows you to change to Pangolin 3 by including `pangolin_version: "3"` in your `config.yaml` file.

**Comment by DarianHole** [comment]
Thanks Richard, no worries there I had a workaround for the time being
